### ISSUE TITLE
Portmaster shows pings from LAN as "coming to VMMS"

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1203] opened 2023-04-29 12:50 UTC
## Reproduce

use nmap to ping all ports on client with portmaster

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by ppacher** [comment] 2023-05-13 07:57
Please fill out the issue template! Those question have a reason because we are limited in resources and just "use nmap to do this and that" is not a bug report!

Closing this until you update the report, feel free to re-open it afterwards

**Closed by ppacher** 2023-05-13 07:57 UTC
Labels: bug
