### ISSUE TITLE
Portmaster FW is crashing my Win10-PC /w DPC Watchdog Violation Error

### ISSUE THREAD

**Issue by Rittmeister39** [safing/portmaster#394] opened 2021-09-21 00:09 UTC
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
PC crashed several times, about once per day

**What did you expect to happen?**:
not crashing my PC

**How did you reproduce it?**:
It happened several times, about once per day, and one time it crashed twice in a row. I unplugged all my USB drives, but it crashed anyway without them. I have now uninstalled Portmaster and replaced it with a Firewall Product that has not crashed once since 7 days. Clearly you have a problem. Good Luck fixing it...

**Debug Information**:

**Comment by dhaavi** [comment] 2021-09-21 08:33
Hey @Rittmeister39, thanks for reporting this issue, even though you have already moved on for a week now!

This seems to be a duplicate of https://github.com/safing/portmaster/issues/385, so I would kindly ask you to continue the discussion there.

If you find the time, two things would help us here:
- Do you have IPv6 enabled on your PC?
- Could you provide us with the raw minidump file?
  - Details in this comment: https://github.com/safing/portmaster/issues/385#issuecomment-923753999

Closing as duplicate of https://github.com/safing/portmaster/issues/385.

**Closed by dhaavi** 2021-09-21 08:33 UTC
Labels: bug
