### ISSUE TITLE
[Suggestions] for Some crucial workflow improvements

### ISSUE THREAD

**Issue by Kiefy** [safing/portmaster#396] opened 2021-09-23 00:05 UTC
I'm not sure if I'm using the program correctly, but what I need mostly is an allow/block for an entire app, not just the current IP/Port. (Though that has it's small case uses too)

So when I get a notification, I have to immediately jump to that App's settings, Click the pencil to unlock access to the Default Action option, then set it to Allow or Block.  This is obviously tedious.

I would find it far more beneficial if the easily accessible Allow/Block buttons right there on the individual connections in the access notification itself had a way to affect the whole app globally as well.

Like this maybe?
![mock-up](https://i.imgur.com/wnuZzND.png)

Actually. If all of this was in a pop-up like [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html) on Mac does it. instead of having to open the Portmaster app at all. well then, that would be something really special.

Little Snitch (When the ... button is pressed)
![Little Snitch](https://i.imgur.com/VHjdMy9.png)
Bonus points for offering extended info in the tooltip like certificates, whois etc on both the APP and the URL, to better make an informed decision.

Maybe even some noob-friendly curated guiding notes for common windows sub-systems with confusing names.
![Noob info](https://i.imgur.com/H2r0yvu.png)

And if we could see at a glance which apps are globally Allowed or Blocked, that would be pretty swell too!

![Another mock](https://i.imgur.com/KtQgz1K.png)

**Comment by LukeSeers** [comment] 2021-09-23 11:27
Hey @Kiefy thanks for giving us great feedback! I fully agree with all the points you have stated. 

The current Prompts is from the very early Portmaster days, but with the newer UI slapped on top of it because it was not high on our priority list. This of course opens up UX problems like yours. 

I do have some good news though. We are planning to have a meeting talking about this topic fairly soon and the direction it should be taken. Your feedback will be very valuable in that regard, so again thank you.

This rework of the Prompts wont be a simple task. One of these problems is supporting a "pop-up like Little Snitch on Mac does it." with different platforms ie linux, windows and mac. We have very lightly discussed that maybe for the time being only making this feature available for windows for the time being, **but this is not set in stone**.

**Tiny note:** I knew this would be a problem down the line since the Prompts was designed with the older Portmaster mind set since UX was not important back then. But, now it's very important and I'm very grateful for you wanting to helping us improve the Portmaster 🙂

**Comment by dhaavi** [comment] 2022-02-11 17:36
Sorry, issue was closed by misconfigured bot.

**Comment by Raphty** [comment] 2023-08-22 11:44
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.

**Closed by Raphty** 2023-08-22 11:44 UTC
Labels: suggestion, backlog, waiting for resources
