### ISSUE TITLE
Windows - slowness opening some sites

### ISSUE THREAD

**Issue by pouriyajamshidi** [safing/portmaster#859] opened 2022-09-17 09:17 UTC
### What happened?

I browse a certain set of sites on a daily basis and on some of them, for example www,gamersyde.com, I notice a huge delay for the page to open and then if I open any article on their site, the slowness keeps on happening so it could not be DNS caching.

This slowness; read how long it takes to open the page is usually more than a minute! So I just click on the site, go do some other stuff and come back when the page is loaded.

I tested the site by not using the Portmaster and it loads instantaneously 

### What did you expect to happen?

The page to load quite fast

### How did you reproduce it?

just visit www,gamersyde.com with postmaster on.

### Additional information

All the settings are default and I am on Cloudflare&#39;s secure DNS, suggested by the application itself.

**Debug-Info**: https://support.safing.io/privatebin/?6edcfa6a9b7e07f8#8qDEUJHQtHyq8VtxrYbEyDeQX7mcKkrV3XKv9tWEE6EZ

**Comment by vlabo** [comment] 2022-09-17 10:32
Thank you for your bug report @pouriyajamshidi.

The problem is that Portmaster is not blocking the connections properly on Windows. This is an issue that we are working on.
[safing/portmaster/issues/430](https://github.com/safing/portmaster/issues/430)

We will add www.gamersyde.com to our testing list.

Closing this issue for now.

**Closed by vlabo** 2022-09-17 10:32 UTC
Labels: bug
