### ISSUE TITLE
Windows BSOD due to DRIVER_IRQL_NOT_LESS_OR_EQUAL error in the kernel extension

### ISSUE THREAD

**Issue by Cmnspro** [safing/portmaster#1019] opened 2022-11-30 14:22 UTC
**What happened**:
Windows shut down due to an error in the portmaster_kext_v1.0.15.sys.
[Image of error screen](https://user-images.githubusercontent.com/54321931/204463430-1504344e-0ee0-4ec3-aab0-538b0c1890e5.jpg)

**What did you expect to happen?**:
That Windows doesn't shut down.

**How did you reproduce it?**:
Unfortunately not able to reproduce it.

**Debug Information**:
Dump already uploaded

**Comment by dhaavi** [comment] 2022-12-02 16:32
We have just released a fix for this problem to the "Beta" channel. Here is how you switch to it: https://github.com/safing/portmaster/issues/717

Please note that this is an emergency fix and it only affects a sub-component, so you will not get a "new version" notification. After switching to the "Beta" channel, wait until you see the "Update Check Successful" notification and then restart Portmaster. In case you are already on the "Beta" channel, download updates to get the fix.

We will be testing the fix a couple days in the "Beta" channel and then release it for everyone.

**Comment by 678720** [comment] 2022-12-03 08:42
Today my Windows 11 Home received updated KB5020044. For an hour I have about 4-5 blue screens caused by "portmaster-kext_v1-0-16.sys". I'm already on beta channel and triggered for update by looks like the fix it's not working for my system.
![Portmaster](https://user-images.githubusercontent.com/30982261/205432327-09135d4b-f938-42f4-9081-dac8a52f5d04.jpg)

**Comment by dhaavi** [comment] 2022-12-03 10:40
Thanks for reporting this. Version 1.0.16 of the kext already is the newest version.

I just set the kext version in the Support Channel to an older version. Can you switch the Support Channel and check if that works okay?

**Comment by dhaavi** [comment] 2022-12-03 11:13
Also, @678720, if you could send us a minidump of one of these crashes, that would be great!
You can upload them here and send the link via email if you want to be more cautious: https://support.safing.io/privatebin/

**Comment by 678720** [comment] 2022-12-03 18:11
> I just set the kext version in the Support Channel to an older version. Can you switch the Support Channel and check if that works okay?

The support channel is working fine, there have been no problems for several hours. Now I tried to enable the beta channel and got a blue screen after a few minutes.
I also sent a link to the minidump to support@safing.io. Hope this helps.

**Comment by vlabo** [comment] 2022-12-05 13:44
We have another bug that is related with the updating of the kernel extension. If Portmaster does not shutdown properly it will not stop the driver service for the kernel extension.  So if Windows crashes before Portmaster stops it will not update the kernel extension.
We are going to fix this with the next release, until then the workaround is to properly shutdown/restart portmaster after update.

**Comment by dhaavi** [comment] 2022-12-07 21:42
We've fixed said bug in Portmaster v1.0.3, which went into the Beta channel today. If you have time to test, please report back if that works for you. We have done extensive testing and believe this to be the final fix for the problem.

**Comment by dhaavi** [comment] 2022-12-08 08:24
Portmaster v1.0.3 is now in stable.

**Comment by dhaavi** [comment] 2022-12-09 11:33
Due to continued issues in v1.0.3, we've rolled back the affected kext sub-component. You don't have to do anything, as the kext will be rolled back after next update check + Portmaster restart.

We are continuing investigation.

**Comment by timsderstrm** [comment] 2022-12-11 17:01
I'm also experiencing this issue on a fresh and updated Windows 10 Home install, It's unusable as of now, i get BSO'D after a while. And I'm paying for SPN. :/

**Comment by dhaavi** [comment] 2022-12-11 21:36
Hey @timsderstrm, thanks for reporting.

We are in the process of fully addressing the DPC_WATCHDOG_VIOLATION BSOD error with the new kext/driver versions. But in these new versions still have other issues. From my understanding, this can occur especially if there are many connections and a lot of traffic going on.

We have already partly addressed this issue in https://github.com/safing/portmaster/issues/385 and https://github.com/safing/portmaster/issues/589.

This issue, however, is about the DRIVER_IRQL_NOT_LESS_OR_EQUAL error in kext versions v1.0.15 and v1.0.16 (note: not PM version, kext version). I will update the issue to better reflect this.

The two faulty versions are NOT (anymore) in Stable or Beta channels.

**Closed** 2023-08-24 05:23 UTC
Labels: bug, waiting for input, windows only
