### ISSUE TITLE
Uninstalling Portmaster on Ubuntu (Derivation) fails

### ISSUE THREAD

**Issue by ghost** [safing/portmaster#414] opened 2021-10-14 03:19 UTC
how to uninstall the postmaster for my system from my linux  system

**Comment by lfom** [comment] 2021-11-11 23:34
Hi, there. I have installed portmaster a while ago using the official deb installer from website. I have disabled its systemd service so it is not running at the background. Coincidentally, I am not using a third party repo that also packages portmaster for Debian/Ubuntu:

```
$ apt policy portmaster
portmaster:
  Installed: 0.5.2.0
  Candidate: 0.7.0~1
  Version table:
     0.7.0~1 100
        100 https://sourceforge.net/projects/madlinux/files/repo core/main amd64 Packages
 *** 0.5.2.0 100
        100 /var/lib/dpkg/status
```

The problem is that the update fails with a weird message about Alpine:

```
Preparing to unpack .../portmaster_0.7.0~1_amd64.deb ...
portmaster: Detected previous installation of Portmaster at
portmaster: /var/lib/portmaster
portmaster: Please uninstall the portmaster package and try again!
portmaster: You settings will be migrated automatically during re-installation.
dpkg: error processing archive /var/cache/apt/archives/portmaster_0.7.0~1_amd64.deb (--unpack):
 new portmaster package pre-installation script subprocess returned error exit status 1
portmaster: post remove of alpine
portmaster: Alpine linux is not yet supported
dpkg: error while cleaning up:
 new portmaster package post-removal script subprocess returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/portmaster_0.7.0~1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

And I cannot uninstall it either using the procedure that is listed in the official documentation:

```
$ sudo apt purge portmaster   
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  portmaster*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 13,3 MB disk space will be freed.
Do you want to continue? [Y/n] 
dpkg: error processing package portmaster (--remove):
 package is in a very bad inconsistent state; you should
 reinstall it before attempting a removal
dpkg: too many errors, stopping
Errors were encountered while processing:
 portmaster
Processing was halted because there were too many errors.
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

As I said, no `portmaster` process is running. What is the proper way to uninstall it? I am running Pop!_OS 21.04 (like Ubuntu 21.04).

Thank you

**Comment by dhaavi** [comment] 2021-11-18 09:26
Hey @lfom, thanks for your detailed report!
Glad to hear you were able to resolve it.

We will look into this - there seems to be a problem with the distro detection.

**Comment by dhaavi** [comment] 2022-02-11 17:36
Sorry, issue was closed by misconfigured bot.

**Closed** 2023-08-22 11:44 UTC
Labels: bug, linux only, next, waiting for resources
