### ISSUE TITLE
Coming back to PM after a year+, very little UI progress..

### ISSUE THREAD

**Issue by TMS-Namespace** [safing/portmaster#507] opened 2022-01-27 11:12 UTC
Hi,

Although I really appreciate the great work you are guys doing, basically for free, there is still lots of place for improvements, (in UI).

For example, blocking/allowing a domain within one app, dose not reflects on domain's green/gray bar immediately..

Still no way to allow/block a particular set of domain connections. Take for example VS code, you may need to allow it to connect to particular domains in particular cases, and then to block it, now you need to do that for each domain, along the hassle, it is really hard to remember which domains you need for each case.

Still no way, to allow/block multiple apps in one click, for example, when I want to update everything on my system, in one run, and then block them back.

Still no way to perform resizing on the vertical splitters between sections.

Application detection is kinda slow, the application starts and tries to connect, but will appear in PM only after a minute or so...

Context menu, on tray icon, sometimes stops from showing up fully, even double clicking dose nothing.

Hopefully, you are considering those essential options for future releases.

**Comment by davegson** [comment] 2022-06-10 07:17
Hey there,

thanks for your kind words and all your input! This definitely helps us understand user needs more

> there is still lots of place for improvements, (in UI).

Yes, we agree. Just some background info, we are a small team with limited resources, we would love to be further than what we are too :). Additionally, the year 2021 we focused a lot of technical stability within the PM and bringing out the SPN.

> Still no way to XYZ

Just as a general response, the "Beta" phase will focus much more on UI improvements than the current "Alpha" phase does.

> For example, blocking/allowing a domain within one app, dose not reflects on domain's green/gray bar immediately..

This works as intended, as the bar shows what happened in the previous 10 minutes. -> "Beta"

> Still no way to allow/block a particular set of domain connections. Take for example VS code, you may need to allow it to connect to particular domains in particular cases, and then to block it, now you need to do that for each domain, along the hassle, it is really hard to remember which domains you need for each case.

Is this like a case where you would like to have block a domain in general but then have a button which says "Allow for 5 minutes" so it can perform an update or whatever? If I misunderstood please clarify

> Still no way, to allow/block multiple apps in one click, for example, when I want to update everything on my system, in one run, and then block them back.

Yeah, application groups is a feature which would be neat, but very tricky in regards to UI. Probably more a thing for "Stable"

> Still no way to perform resizing on the vertical splitters between sections.

Good news, we plan to make things more compact on this side in a PM version which is already being developed on. Won't be able to resize, but the app overview will be _below_ the shield, creating much more space.

> Application detection is kinda slow, the application starts and tries to connect, but will appear in PM only after a minute or so...
> Context menu, on tray icon, sometimes stops from showing up fully, even double clicking dose nothing.

If these technical issues still happen I would ask you to open a bug report.

Anyway, I will close this collection of issues since it does not fit the issue format - BUT I will forward this to our Product Owner so he gets all of this input too. In our project management, we create lots of task which then get to compete with each other - cannot guarantee when certain things will be tackled, but can guarantee we hear you!

**Closed by davegson** 2022-06-10 07:17 UTC
Labels: suggestion
