### ISSUE TITLE
Bandwidth control

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#617] opened 2022-04-22 15:14 UTC

**Comment by itsnotsaved** [comment] 2022-04-26 06:21
> @dhaavi Example, I want to limit upload speed for browser to every low "500Kbps" but down speed to highest. But I want my VPN app to have 1000kbps up and down to max.

https://github.com/safing/portmaster/issues/382

**Comment by davegson** [comment] 2022-06-23 08:11
closing as a duplicate of #382

**Closed by davegson** 2022-06-23 08:11 UTC
Labels: suggestion
