### ISSUE TITLE
Add option to create 'App Profiles' by Path. Ex- C:\Windows\*

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#892] opened 2022-09-24 08:54 UTC
Example - C:\Program Files\Internet Explorer\*

Useful when an app uses many exe

**Comment by ppacher** [comment] 2022-09-25 17:38
Duplicate of https://github.com/safing/portmaster/issues/485

**Closed by ppacher** 2022-09-25 17:38 UTC
Labels: suggestion

**Comment by Rexadev** [comment] 2023-05-30 18:42
@ppacher it is not the duplicate of that
