### ISSUE TITLE
Add support for High DPI (HiDPI) and set scaling factors

### ISSUE THREAD

**Issue by NicolasGoeddel** [safing/portmaster#692] opened 2022-06-10 10:04 UTC
**What would you like to add or change?**:
When using (Ubuntu) Gnome I am able to set fractional scaling per display. This is, for example, useful with a 4K display. Without the scaling UI elements and text are very small and hard to read from a distance. This is how that setting looks like on my German system:
![grafik](https://user-images.githubusercontent.com/1520064/173040711-a7753707-353f-4a63-b8ae-ee1f849fa5fd.png)

On the system I made the screenshot I have no high DPI display connected but I have on an other one where I am not logged into Github right now.

However I would really appreciate adding support for scaling factors. I don't know how exactly this works in conjunction with Wayland or X but I hope you can figure it out. It seems supporting scaling is still a somehow new concept in the Linux world.

**Why do you and others need this?**:
We need it to not being forced to pinch our eyes or stand up from the couch to figure out what nice things Portmaster wants to show us.

**See also**
https://wiki.archlinux.org/title/HiDPI

**Comment by davegson** [comment] 2022-06-15 07:41
hey there, thanks for your suggestion!

this is a duplicate of https://github.com/safing/portmaster-ui/issues/233, so I'm closing it here.

On the other issue a possible "quickfix" is discussed which you might use for the moment

**Closed by davegson** 2022-06-15 07:41 UTC
Labels: suggestion
