### ISSUE TITLE
Flatpak build 

### ISSUE THREAD

**Issue by LeandroStanger** [safing/portmaster#1195] opened 2023-04-28 00:39 UTC
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing **Portmaster** on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by dhaavi** [comment] 2023-04-28 06:29
Duplicate of https://github.com/safing/portmaster-packaging/issues/43.

**Closed by dhaavi** 2023-04-28 06:29 UTC
Labels: bug
