### ISSUE TITLE
Win safing firewall backup Function.. No button?

### ISSUE THREAD

**Issue by oklokl** [safing/portmaster#825] opened 2022-09-02 12:51 UTC
**What would you like to add or change?**:
I have a backup function. I want to add a button.
It would be nice if a password protection lock function was added.

And I'm from Seoul Korea. I can't speak English.
I want to translate notification speech bubble with Google.

And if the user wants, it would be nice to provide a light translation language through Google Translate.

If you do that, various users around the world will translate English through Google Translate, which will make it more accessible.

https://cafe.daum.net/candan/BLQD/75
I translated it into Korean through Google Translation

**Why do you and others need this?**:

**Comment by dhaavi** [comment] 2022-09-15 10:13
Hey @oklokl, thanks for the suggestion.

We arleady have a simple backup option planned for settings and app settings. We will iterate from there.

Translations are a bit further out, but will definitely come!

(Please do not combine different suggestions in one issue in the future.)

**Comment by dhaavi** [comment] 2022-09-15 10:14
I'm closing this as a duplicate of https://github.com/safing/portmaster/issues/388

**Closed by dhaavi** 2022-09-15 10:14 UTC
Labels: suggestion
