### ISSUE TITLE
Portmaster triggering BSOD with DPC_WATCHDOG_VIOLATION error

### ISSUE THREAD

**Issue by Duschmolll** [safing/portmaster#385] opened 2021-09-05 03:28 UTC
Hello,

**What happened**: I was simply running my PC and after 15-20mins it crashed. I've look on the log of windows and Pormaster came out.

**How did you reproduce it?**: It happened again and no clue why. I was simply using my PC doing some skin for rainmeter, no high use of CPU. It's the third time my PC crash since installing it on my PC, I can't tell if the first one came from Portmaster, but the second and third are confirm by windows crash log. Windows was reinstall about a week ago, so it quite fresh too.

**Debug Information**: Here is the debug log from Windows, I can upload it if needed.
```
DPC_WATCHDOG_VIOLATION (133)
The DPC watchdog detected a prolonged run time at an IRQL of DISPATCH_LEVEL
or above.
Arguments:
Arg1: 0000000000000000, A single DPC or ISR exceeded its time allotment. The offending
    component can usually be identified with a stack trace.
Arg2: 0000000000000501, The DPC time count (in ticks).
Arg3: 0000000000000500, The DPC time allotment (in ticks).
Arg4: fffff80426cfa320, cast to nt!DPC_WATCHDOG_GLOBAL_TRIAGE_BLOCK, which contains
    additional information regarding this single DPC timeout

SYMBOL_NAME:  portmaster_kext_v1_0_10+2238

MODULE_NAME: portmaster_kext_v1_0_10

IMAGE_NAME:  portmaster-kext_v1-0-10.sys

STACK_COMMAND:  .thread ; .cxr ; kb

BUCKET_ID_FUNC_OFFSET:  2238

FAILURE_BUCKET_ID:  0x133_DPC_portmaster_kext_v1_0_10!unknown_function

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {79ebff84-ca6f-e38b-6515-877cc7e1cb3d}
```
My components are :
```
redacted
```
The applications that were running from memory are: (My PC was booted for less than 15minutes, I launched it to watch F3 race)
```
redacted
```

I have since uninstalled Portmaster, no crash to report, I look forward to this issue being fixed and reinstalling Portmaster.

**Comment by dhaavi** [comment] 2021-09-06 09:02
They @Duschmolll, thanks for reporting this issue here and on chiming on Reddit!

As a reference for other readers, here is the reddit thread: https://www.reddit.com/r/safing/comments/peybt4/portmaster_triggering_bsod_w_crash_memory_dump/

I seems that the Kernel Extension is spending too much time somewhere. I've looked into it briefly and haven't found an obvious offender. Looking into this will take a little more time and I hope to be able to dedicate time to this soon.

Here are some questions to help me get started in the right direction:

- Were you using the `Prompt` [Default Action](https://docs.safing.io/portmaster/settings#filter/defaultAction) somewhere?
  - If so, were there many pending prompts waiting to be handled?
- Do you have IPv6, or IPv4 only?
- What did the network activity look like at the time of the crash?
  - Were you downloading something? Ie. was there a connection with lots of data?
  - Were many applications active on the network? Ie. were there many small connections?

**Comment by Duschmolll** [comment] 2021-09-06 09:12
No worries, happy to help in any way.

**Were you using the Prompt Default Action somewhere?** I did not use `Prompt `anywhere.

**Do you have IPv6, or IPv4 only?** I do not know exactly, when I do ipconfig on cmd, I have IPv6 and IPv4 showing.

**What did the network activity look like at the time of the crash?** I was quite using my connection, through VLC to get the official F3 broadcast. I was using a tiers party software that redirect the flow of the stream through VLC or other media program. It's a 1080p video broadcast.

At the third crash, I don't remember if I was actually downloading or watching something, sorry.

As for the small connexion based on the software opened:
```
Mozilla Thunderbird - small
F1Viewer - small
VLC - heavy
Rainmeter - none
HWiNFO64 - none
Portmaster 
NVIDIA Settings - none
Wallpaper Engine - none
Logitech G Hub - none
AutohidedestopIcon -none
f.lux - none
keepass XC - none
```

So I guess not that many small

**Comment by sydbarrett74** [comment] 2021-09-09 23:24
I've been having the *exact* same problem, with lots of BSOD's the last few days due to Portmaster. Usually it happens if I'm watching a video on Youtube, playing World of Warcraft, or checking Gmail. I'll provide my system info and then a link to the minidump on Pastebin.

Alienware m15 R3 / Windows 10 Pro 21H1 / 32GB RAM / 2TB SSD

Minidump link: [https://pastebin.com/PQU6dSFA](https://pastebin.com/PQU6dSFA)

**Comment by dhaavi** [comment] 2021-09-13 14:13
Hey @sydbarrett74, thanks for adding more detail to this issue.

My current hunch is that this might be related to IPv6. If anyone of you finds the time to disable IPv6 on their PC and try again that would be great!

@sydbarrett74: Do you have IPv6 on your PC?

**Comment by sydbarrett74** [comment] 2021-09-15 03:37
@dhaavi I do have IPv6 enabled on all of my interfaces. I will disable and retry.

**Comment by dhaavi** [comment] 2021-09-21 08:25
@sydbarrett74, thanks for checking for that for me!

In order to fully analyze the crash, could you provide us with the raw minidump file? This can normally found in `C:/Windows/Minidump/*.dmp`, see [this post for more details](https://serverfault.com/questions/306812/where-is-minidump-file).
This would help us pinpoint the problem a lot easier and more confidently.

As this might contain sensitive data, please upload it [here](https://support.safing.io/privatebin/) and then send us the link privately via email at support@safing.io.

**Comment by Rittmeister39** [comment] 2021-09-21 09:09
My Win10 PC crashed several times also after I started using Portmaster and had blocked a bunch of stuff in the Firewall.
I will attach the dump files. My Win10 version is modified, it has some parts cut out, like updates, MS store, and explorer is also replaced. It's called Win10 AME (ameliorated), you can find it online. But that is not the Issue really, because other Firewall software has not caused the PC to crash in over a year before I tried out Portmaster, and also not since I uninstalled Portmaster.
Good luck fixing and improving your Software. Too bad, I would have preferred some open source solution.
[Minidumpfiles Win10crash DPC Watchdog Violation.zip](https://github.com/safing/portmaster/files/7201898/Minidumpfiles.Win10crash.DPC.Watchdog.Violation.zip)

**Comment by sydbarrett74** [comment] 2021-09-23 23:29
Just checking in to see if my minidump was at all helpful. :)

**Comment by 3dWrecker** [comment] 2021-10-04 23:18
Also have the same issue - version 6.22. Crashed during Uni tests two days in a row before I dug into the dumps 🙄.

**Comment by dhaavi** [comment] 2021-10-05 15:10
We have now tested and merged the potential fixes with https://github.com/safing/portmaster-windows-kext/pull/12 and are now waiting for our new EV Code Signing Certificate to be issued to deploy the update. This depends on the CA and we cannot exactly tell how long it will take - at least some more days, up to 1-2 weeks in the worst case.

**Comment by sydbarrett74** [comment] 2021-10-06 05:08
I look forward to testing it. I also upgraded to Windows 11 last night, so
that'll be interesting to test against.

**Comment by dhaavi** [comment] 2021-10-08 06:59
While the CA has completed validation, it seems we have hit an edge case in their certificate issuing process. We are in contact with them and waiting for them to resolve this.

Sorry for the delay and getting your hopes up. I originally wanted to have it released within hours of my last message.

**Comment by dhaavi** [comment] 2021-10-08 17:30
The (potential) fix is now released on the Beta [Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel) in [v1.0.11 of the Kernel Extension](https://github.com/safing/portmaster-windows-kext/releases/tag/v1.0.11). 🎉

Whoever finds the time and was able to reliably reproduce the problem, please test it and report back!
Be sure you on the Beta channel!

If you have already upgraded to Portmaster v0.7.2, you can manually trigger the update and restart Portmaster in order for the new Kernel Extension to become active. You can always check the currently used version in the version dropdown in the settings.

**Closed** 2021-11-22 10:39 UTC
Labels: bug, waiting for fix confirmation

**Comment by sapnaarora25** [comment] 2023-03-03 04:51
You can see this article for details on [how to fix dpc watchdog violation](https://thedigitalbin.com/how-do-i-fix-dpc-watchdog-violation-in-windows-10-11/) error.

**Comment by BenedictLang** [comment] 2026-04-23 22:19
Just leaving a comment as I get BSOD WATCHDOG and using portmaster. But havent looked into my logs yet. Just read about graphic driver issues and clean reinstallation would help, but it didnt. Going to investigate when I have more time
