### ISSUE TITLE
Unable to download assets / install: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by dhaavi** [safing/portmaster#571] opened 2022-03-16 13:26 UTC
Hi,
i can't download the 300mb, i tried manually and i've got
" [control] 2022/03/16 11:11:01 WARNING: error loading indexes: failed to download index stable.json: failed to make request to "https://updates.safing.io/stable.json": Get "https://updates.safing.io/stable.json": x509: certificate signed by unknown authority
Error: failed to download index stable.json: failed to make request to "https://updates.safing.io/stable.json": Get "https://updates.safing.io/stable.json": x509: certificate signed by unknown authority"

can you help me ? :-)

_Originally posted by @pommedefrance in https://github.com/safing/portmaster/issues/534#issuecomment-1069110809_

**Comment by dhaavi** [comment] 2022-03-16 13:29
Hey @pommedefrance, thanks for raising this issue.

This is most likely due to your system being out of date.
What system are your running - and which version are you using?

**Comment by pommedefrance** [comment] 2022-03-16 14:14
euh that old ;-) win10 x64 version 2009 build 19043.1165...

**Comment by dhaavi** [comment] 2022-03-16 14:23
I couldn't find if that version of Windows should already have the root certificate or not, you read more about the root we are using - Let's Encrypt R3 - here:
https://letsencrypt.org/certificates/

Chromium-based browser should have the same problem, as they also use the Windows Root Store. This might be easier for testing.

**Comment by pommedefrance** [comment] 2022-03-16 20:30
yes it works, at least portmaster ! but i don't have internet at all anymore..portmaster says limited connexion and can't update...perhaps, i miss something to let the access...because when i uninstall all, internet ame back..
thks..

**Comment by northys** [comment] 2022-03-18 09:15
@pommedefrance you can find a doc about installing certs in windows here https://docs.microsoft.com/en-us/skype-sdk/sdn/articles/installing-the-trusted-root-certificate

here you can download r3 pem root cert https://letsencrypt.org/certs/lets-encrypt-r3.pem (source https://letsencrypt.org/certificates/)

after you import the CA you can try installing portmaster again. lemme know if that helped.

**Comment by pommedefrance** [comment] 2022-03-18 10:15
yes i told that it's working (but i put the certificate everywhere, i don't know where exactly)...but still no luck with internet..portmaster blocks everything for now :-(
thks

**Comment by northys** [comment] 2022-03-18 11:02
@pommedefrance can you access the portmaster UI? can you send us a screen so we can see what it says?

**Comment by pommedefrance** [comment] 2022-03-18 18:13
yes it's better when my firewall (windows) is off..but i allowed everything for portmaster then i don't know what's wrong...and i try another time with the firewall and it's ok ??
still have network connectivity limited ? (see the png)
and in thunderbird can't receive yahoo and gmail email..
it says certificate pb as the install...i'll send the exact message..

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/37299047/159059812-5aea9f02-7f81-42f9-8d69-69e5aebd8824.PNG">

**Comment by northys** [comment] 2022-03-18 19:04
isn't there more information when you click on the `Limited network connectivity` notification?

---

can you run those 3 commands in powershell / command line?

```
nslookup safing.io 1.1.1.1
nslookup safing.io
ping safing.io
```

**Comment by pommedefrance** [comment] 2022-03-19 08:53
nslookup safing.io 1.1.1.1
DNS request timed out.
    timeout was 2 seconds.
Serveur :   UnKnown
Address:  1.1.1.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Le délai de la requête sur UnKnown est dépassé.
for the nslookup..
Limited network connectivity.
Portmaster did detect local network connectivity, but could not detect connectivity to the Internet.
and for gmail and yahoo same message
query failed: all 2 query-compliant resolvers failed, last error: query failed: failed to connect to AppliedPrivacy (dot://94.130.106.88:443#config): x509: certificate has expired or is not yet valid:

**Comment by northys** [comment] 2022-03-23 01:32
@pommedefrance sorry I forgot to reply.

Can you please confirm that https://safing.io/ works for you in all browsers you have available when you don't use portmaster?

I would love to see results Internet Explorer (or Edge or whatever comes with your Win installation) and Firefox or Chrome. If you can test all 3, that would be the best.

Safing.io uses the new R3 website... Actually half of the internet runs on this new R3 let's encrypt root CA...

---

The problem is that your system (individual browsers may have their own certificate manager and ignore system certs). By default portmaster uses **D**ns **O**ver **T**ls (DOT). That means the connection to the DNS server is encrypted as any other **HTTPS** website. HTTPS and DOT use the same type of cert to encrypt the transport layer.

> In HTTPS, the communication protocol is encrypted using Transport Layer Security (TLS) or, formerly, Secure Sockets Layer (SSL). The protocol is therefore also referred to as HTTP over TLS, or HTTP over SSL.

If (for some magic reason) most of the internet works for you when you don't use portmaster (and I would say that only because you use browser which manages those root certificates itself) we should focus on whether you have really R3 let's encrypt CA installed. I don't have any idea what it shouldn't. It just doesn't make sence :(

EDIT: it can be even different CA because I see you picked adguard in DNS which uses zerossl CA

**Comment by northys** [comment] 2022-03-23 01:33
PLEASE SET THE DNS ONLY TO `tcp://1.1.1.1` (unencrypted plain old dns which we used since DNS was born) AND TRY THE FOLLOWING AGAIN:

> can you run those 3 commands in powershell / command line and show me the output?
> 
> ```
> nslookup safing.io 1.1.1.1
> nslookup safing.io
> ping safing.io
> ```

**Comment by pommedefrance** [comment] 2022-03-23 08:56
no pb for safing.io in the browser..chrome, librefox, firefox

nslookup safing.io 1.1.1.1
Serveur :   one.one.one.one
Address:  1.1.1.1

Réponse ne faisant pas autorité :
Nom :    safing.io
Address:  185.199.109.153

nslookup safing.io
Serveur :   one.one.one.one
Address:  1.1.1.1

Réponse ne faisant pas autorité :
Nom :    safing.io
Address:  185.199.109.153

ping safing.io (with firewall but everything is allowed !!)

Envoi d’une requête 'ping' sur safing.io [185.199.109.153] avec 32 octets de données :
Défaillance générale.
Défaillance générale.
Défaillance générale.
Défaillance générale.

Statistiques Ping pour 185.199.109.153:
    Paquets : envoyés = 4, reçus = 0, perdus = 4 (perte 100%),

ping safing.io (without firewall)

Envoi d’une requête 'ping' sur safing.io [185.199.109.153] avec 32 octets de données :
Réponse de 185.199.109.153 : octets=32 temps=39 ms TTL=54
Réponse de 185.199.109.153 : octets=32 temps=56 ms TTL=54
Réponse de 185.199.109.153 : octets=32 temps=46 ms TTL=54
Réponse de 185.199.109.153 : octets=32 temps=43 ms TTL=54

Statistiques Ping pour 185.199.109.153:
    Paquets : envoyés = 4, reçus = 4, perdus = 0 (perte 0%),
Durée approximative des boucles en millisecondes :
    Minimum = 39ms, Maximum = 56ms, Moyenne = 46ms

**Comment by northys** [comment] 2022-03-23 11:48
by firewall you mean portmaster itself that windows deffender firewall? iirc ping should work just fine when portmaster is in default trusted mode :/

anyway resolving seems to be working for you with plain dns withour encryption from what I can see. **does that mean thunderbird can connect now when you have set the tcp://1.1.1.1 resolver?**

---

later when i get bored i'll try to download some old windows (probably win7) and try to replicate your problem with portmaster not trusting the cert of DOT nameserver. also i'll try to fix it by installing lets encrypt r3 CA.

**Comment by pommedefrance** [comment] 2022-03-23 17:08
yes windows firewall
thunderbird with postmaster, i've all my mails except yahoo and gmail...certificate error..

**Comment by northys** [comment] 2022-03-23 21:44
okay and i have to ask a dump question - when you turn off portmaster you don't get cert err for yahoo and gmail in thunderbird? because that seems to be really weird.

if it works when you turn off portmaster can you please run nslookup command for imap.gmail.com and imap.mail.yahoo.com? run it while portmaster is on and off so we can see if there is a difference.

**Comment by ZzZombo** [comment] 2022-03-24 04:24
I'll bump this issue, for me this is because I have set up an HTTP decrypting proxy globally on my system. On option either to ignore TLS errors (not recommended, of course) or to accept my CA certificate as trusted would be nice.

**Comment by northys** [comment] 2022-03-24 11:25
@ZzZombo you mean something like man in the middle attack performed on your computer by some antivirus software like avast.com?

**Comment by pommedefrance** [comment] 2022-03-24 18:45
after a restart, i don't have internet at all anymore :-(..
but postmaster update says ok..
and i've got the message again for firefox and thunderbird..
"query failed: all 2 query-compliant resolvers failed, last error: query failed: failed to connect to AppliedPrivacy (dot://94.130.106.88:443#config): x509: certificate has expired or is not yet valid:"

**Comment by dhaavi** [comment] 2022-03-25 14:38
Hey all, thanks for digging into this.

The Portmaster does _not_ change any network traffic. So, in general any TLS activity would need to be identical with or without the Portmaster running. As the Portmaster has no hand in this, it is also not possible to have it accept certificates as trusted.

If there suddenly are certificate errors with the Portmaster enabled, it could be that the OS is configured to hard fail on OCSP/CRL failures. But I have never seen this enabled, because it would potentially leave many websites broken.
Here's an blog post with more info on this: https://scotthelme.co.uk/revocation-is-broken/

The original error reported was `certificate signed by unknown authority`.
As I currently see it, there are only two scenarios how this can happen:
- The CA does not exist within the OS.
- The network packet holding the certificate has been corrupted.

To check if the certificate arrives correctly, please go to https://safing.io/ and [open the certificate](https://www.howtogeek.com/292076/how-do-you-view-ssl-certificate-details-in-google-chrome/).

Please then select "R3" and then "SHA-256 Fingerprint" and post a screenshot of the result. Like this:
![image](https://user-images.githubusercontent.com/18184155/160141410-34e788da-a885-43ec-b653-3eff25fcb1ce.png)

**Comment by pommedefrance** [comment] 2022-03-25 17:38
thks for the response
in firefox/librefox, i've got no pb to go to safing.io....and the SHA-256 Fingerprint is like you show..
no internet in the browser when portmaster is on, thunderbird now i've gmail..but not yahoo....strange

**Comment by ZzZombo** [comment] 2022-03-26 09:07
> Hey all, thanks for digging into this.
> 
> The Portmaster does _not_ change any network traffic. So, in general any TLS activity would need to be identical with or without the Portmaster running. As the Portmaster has no hand in this, it is also not possible to have it accept certificates as trusted.
> 
> If there suddenly are certificate errors with the Portmaster enabled, it could be that the OS is configured to hard fail on OCSP/CRL failures. But I have never seen this enabled, because it would potentially leave many websites broken. Here's an blog post with more info on this: [scotthelme.co.uk/revocation-is-broken](https://scotthelme.co.uk/revocation-is-broken/)
> 
> The original error reported was `certificate signed by unknown authority`. As I currently see it, there are only two scenarios how this can happen:
> 
> * The CA does not exist within the OS.
> * The network packet holding the certificate has been corrupted.
> 
> To check if the certificate arrives correctly, please go to [safing.io](https://safing.io/) and [open the certificate](https://www.howtogeek.com/292076/how-do-you-view-ssl-certificate-details-in-google-chrome/).
> 
> Please then select "R3" and then "SHA-256 Fingerprint" and post a screenshot of the result. Like this: ![image](https://user-images.githubusercontent.com/18184155/160141410-34e788da-a885-43ec-b653-3eff25fcb1ce.png)

I think you misunderstood at least my comment (but I also believe the OP). In my case there was a MitM-proxy already in my system, **prior to installing the software**. When the installer got to the point of downloading the 300 MB update, it failed because it didn't trust the proxy-issued TLS certificate. Please reread my comment in light of this clarification.

**Comment by northys** [comment] 2022-03-26 12:55
> I think you misunderstood at least my comment (but I also believe the OP). In my case there was a MitM-proxy already in my system, **prior to installing the software**.

I think this is different issue as @pommedefrance did not mention MitM-proxy. Would you mind creating new issue? This one seems to be more like "certs behaves weirdly when portmaster is running" and yours is "i can:t install portmaster because it doesn't trust my self signed cert from proxy".

**Comment by dhaavi** [comment] 2022-03-28 15:07
Creating a separate issue for the MitM-proxy is a good idea - but I think this repo is correct for it, as portmaster-start is also developed here.

I will also mark the last two comments as off-topic as they are about another issue.

**Comment by northys** [comment] 2022-03-30 07:00
> almost everything is ok...

so your thunderbird no longer complains about certificates but there is "no internet" warning in portmaster?

> perhaps because i'm sharing my 4g

your operator probably can block something which would lead to this message but i wouldn't expect that in france. i do not have such problem when i tether my 4g here in czechia.

**Comment by Raphty** [comment] 2023-08-22 11:49
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.

**Closed by Raphty** 2023-08-22 11:49 UTC
Labels: bug, in/compatibility
