### ISSUE TITLE
Clicking on Invalid Rule Clears all Rules

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#723] opened 2022-07-05 16:01 UTC
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

Instead it should point what is invalid

**Comment by p2anav** [comment] 2022-07-06 06:12
I checked and that is definitely a bug.

**Comment by davegson** [comment] 2022-07-06 14:19
duplicate of #580

**Closed by davegson** 2022-07-06 14:19 UTC
Labels: bug
