### ISSUE TITLE
Portmaster fails to initialize Windows Kext after internal restart, fails with 0x422

### ISSUE THREAD

**Issue by MPeti1** [safing/portmaster#200] opened 2020-11-26 18:39 UTC
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:
Portmaster says it's in failure state after starting the GUI
![image](https://user-images.githubusercontent.com/9215491/100379971-2e5a0f80-3016-11eb-8e6d-05e05c6de156.png)

**What you expected to happen**:
Portmaster to start successfully

**How to reproduce it (as minimally and precisely as possible)**:
It might have to do something with the `stop portmaster` option on the setting page, but more on this below

**Anything else we need to know?**:
Before I begin, I know this should be broken up to more issues later, but I don't want to litter the issues section until it's farily certain that I haven't screwed up anything, or I don't misunderstand something. [The main part begins here](#main)

I've installed Portmaster on my main OS a few minutes ago. It's not the first time, I like to check in at major updates, and seeing the current state I thought this could be the perfect time to start having Portmaster every day on my main OS.

After a reboot, when I opened the GUI first, it worked properly, applications were listed that were initiating connections, and it had the lock with the green background at the top left.
Shortly after that I noticed that Firefox can't load everything (I can give more details if needed). Checked in the network monitor section for Firefox, and found that an incoming lan connection has been blocked from the IP of my DNS server (Pi-Hole).
On my laptop I've seen that when I click the cog at the right side of a network event, an application specific settings menu opens with the setting being highlighted that would affect the event. That time I haven't seen that yellow marker, so until I found out what's the problem I wanted to stop portmaster's filtering so I could use Firefox again.
It lead to the Portmaster GUI endlessly showing the "disabling" overlay, but I've seen that the core service has been stopped, and also that the kext has been disabled and stopped. I though okay, probably that's how it gets disabled, but it was weird because I thought drivers can't be stopped on-the-fly, without restarting the system.
Then I started the Portmaster GUI, but it showed a blank page until I manually started the core service. Now the GUI was able to load the contents, but this is what I can't solve manually for now.

<h3 id="main">The relevant (to the issue) part</h3>

Portmaster looks like the screenshot above.
I checked and the PortmasterKext driver is actually stopped and disabled, but I can't change it's start type because Windows says `The Specified Service has been marked for deletion.`

**Environment**:
Windows 10 1903
Simplewall is installed, but it's been disabled before reboot

Portmaster Version: 0.6.0 (24.11.2020)

<details>
  <summary>Versions from the `About` page in Portmaster's UI</summary>
If that's the dropdown menu at the top of the settings, I'm not sure how to copy it's contents
</details>

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [x] Windows 10
- [ ] Linux
  - Please provide the output of `cat /etc/os-release`

Logs:
The core logs, with nameserver and connection lines removed: [core.zip](https://github.com/safing/portmaster/files/5604535/core.zip)

**Comment by MPeti1** [comment] 2020-11-26 21:16
I've reinstalled Portmaster a few times, and it seems the PortmasterKext driver always gets marked for deletion, and also disabled. Before clicking "reboot now" in the installer the driver can't be seen in the services list, but at the time I get logged in it's always disabled and marked for deletion, both if I run the installer while Portmaster is installed, and both if I run it after first uninstalling and rebooting

**Comment by dhaavi** [comment] 2020-11-26 21:28
I will take a deeper look at this tomorrow, but I do want to mention one important thing right away. After uninstalling, you need to reboot right away, _before_ installing again.

**Comment by MPeti1** [comment] 2020-11-27 10:31
> 
> 
> I will take a deeper look at this tomorrow, but I do want to mention one important thing right away. After uninstalling, you need to reboot right away, _before_ installing again.

Yes, I did it that way

**Comment by dhaavi** [comment] 2020-11-27 11:00
> I've installed Portmaster on my main OS a few minutes ago. It's not the first time, I like to check in at major updates, and seeing the current state I thought this could be the perfect time to start having Portmaster every day on my main OS.

Great! We think so too.

> Shortly after that I noticed that Firefox can't load everything (I can give more details if needed). Checked in the network monitor section for Firefox, and found that an incoming lan connection has been blocked from the IP of my DNS server (Pi-Hole).

More details would be very interesting here. I think the issue with Firefox may be a known bug that we are currently trying to fix where sometimes dns responses are broken. If this happens, you can clear the DNS Cache from the dropdown menu next to the "Download Updates" button on the settings page.

That Firefox would have an incoming connection from your Pi-Hole is unusual. The Portmaster should actually intercept all DNS requests and handle it itself. Did you change the DNS servers in Portmaster?

> That time I haven't seen that yellow marker, so until I found out what's the problem I wanted to stop portmaster's filtering so I could use Firefox again.

It could be that the setting it wanted to scroll to is not shown because of the active UI Mode. You can switch to "Advanced" in the top right corner, or even "Developer" in the settings. Also, some features aren't stable yet, and you can see them when you change the "Feature Stability" setting.

> It lead to the Portmaster GUI endlessly showing the "disabling" overlay, but I've seen that the core service has been stopped, and also that the kext has been disabled and stopped. I though okay, probably that's how it gets disabled, but it was weird because I thought drivers can't be stopped on-the-fly, without restarting the system.

Drivers can be loaded and unloaded live, to some extent. Interestingly, the Portmaster Kext Service does not even show up for me.

> I checked and the PortmasterKext driver is actually stopped and disabled, but I can't change it's start type because Windows says `The Specified Service has been marked for deletion.`

This really interesting. I will have to investigate further. As far as I understand, `marked for deletion` means it will be deleted on shutdown.

> **Environment**:
> Windows 10 1903

Maybe updating to a newer version helps. What flavor are you running? (Home, Pro, ...)

> Yes, I did it that way

Ok, great!

**Comment by dhaavi** [comment] 2020-11-27 11:12
I've also seen that you've exceeded the maximum buffer size amount for the interface responsible for getting the process attribution data from Windows. You must have had loads of connections there! This should have cause connections to show up in the "Unidentified Processes" App instead of the correct one (eg. Firefox).
If you have other settings enabled there, this may have also caused unexpected behavior. 

I've increased the max size now, which will be in the next release.

But this should not have caused the other issue with the driver.

**Comment by MPeti1** [comment] 2020-11-27 12:49
>>Shortly after that I noticed that Firefox can't load everything (I can give more details if needed). Checked in the network monitor section for Firefox, and found that an incoming lan connection has been blocked from the IP of my DNS server (Pi-Hole).

> More details would be very interesting here. I think the issue with Firefox may be a known bug that we are currently trying to fix where sometimes dns responses are broken. If this happens, you can clear the DNS Cache from the dropdown menu next to the "Download Updates" button on the settings page.

I'll try that out, thank you!
What actually happened there is that I had a Twitch stream opened in a pinned tab before the reboot, and after it I've seen the layout and color scheme has roughly loaded, but the player, the chat and other "live-refreshing elements" (e.g. whole left sidebar) didn't load. I haven't checked other tabs at that time. Also, I don't have DOT set up in Firefox itself. Let me know if there are more details that would be helpful for this.

> Did you change the DNS servers in Portmaster?

First I haven't modified it, but later I added this to be the only one: `dns://192.168.0.30?name=Pi-hole_Home&blockedif=zeroip`

> Interestingly, the Portmaster Kext Service does not even show up for me.

You mean in the logs, or in `services.msc`? I use Process Hacker, that's where I looked for them:
![image](https://user-images.githubusercontent.com/9215491/100448354-6d3da300-30b2-11eb-889c-5d58e59201d6.png)
(They are temporarily disabled)

> This really interesting. I will have to investigate further. As far as I understand, marked for deletion means it will be deleted on shutdown.

I can confirm this, if I don't run the installer again before a reboot, the driver will be gone after it.
I'm thinking if I could use sysmon to log if a service's state is modified, I'll need to look up it's docs for it.

> Maybe updating to a newer version helps. What flavor are you running? (Home, Pro, ...)

It's a Pro. Actually, I have bad experience from always using the latest major version (of Windows), I like to use the one that was released 1 year earlier. They still get updates, and in this time they can fix new bugs, and tutorials can get written for those that they don't. Also, I'm afraid of it breaking a lot of things and introducing unwanted features that I need to find a way to turn off, and on for things they removed. I usually schedule these to the spring and summer.
I make daily backups, so I could try what would happen on 20H2 if you would like

>You must have had loads of connections there!

Umm, yeah. :D I don't like to delete Linux ISO's just because I currently don't need them. I might be the only one that still has that one ISO
I've just noticed that I forgot to start qB again, but after 5 minutes I already have a "few" connections, and they are always opening and closing. At the moment, these are connections with 15-25 peers:
![image](https://user-images.githubusercontent.com/9215491/100450447-ee4a6980-30b5-11eb-9020-ac590892218a.png)

> This should have cause connections to show up in the "Unidentified Processes" App instead of the correct one (eg. Firefox).

So this is how they appear!
Is there another reason they could? Asking because they appear on my laptop too, but I don't run heavy software there (it couldn't bear it)

**Comment by MPeti1** [comment] 2020-11-27 12:50
Again, sorry for including everything in this one issue. Should I break them up into more issues in some way?

**Comment by dhaavi** [comment] 2020-11-27 21:10
> What actually happened there is that I had a Twitch stream opened in a pinned tab before the reboot, and after it I've seen the layout and color scheme has roughly loaded, but the player, the chat and other "live-refreshing elements" (e.g. whole left sidebar) didn't load. I haven't checked other tabs at that time. Also, I don't have DOT set up in Firefox itself. Let me know if there are more details that would be helpful for this.

Yup. Sounds exactly like the issue we are investigating: #203. 

> First I haven't modified it, but later I added this to be the only one: `dns://192.168.0.30?name=Pi-hole_Home&blockedif=zeroip`

👌

> You mean in the logs, or in `services.msc`? I use Process Hacker

Ah! I checked with `services.msc`. Process Hacker looks nice, will check it out! I normally use process explorer for more advanced stuff.

> I can confirm this, if I don't run the installer again before a reboot, the driver will be gone after it.
> I'm thinking if I could use sysmon to log if a service's state is modified, I'll need to look up it's docs for it.

Ok, well that's good. So the issue we are discussing is that you cannot stop and then start the Portmaster without reboot, correct? Because when you stop the Portmaster it marks the Kext for deletion?

> It's a Pro. Actually, I have bad experience from always using the latest major version (of Windows)
> I make daily backups, so I could try what would happen on 20H2 if you would like

Good. I fully understand.
I don't think we need to go down that route yet, maybe later if we don't find anything else.
Just wanted to check if you were wanting to upgrade anyway.

> Umm, yeah. :D I don't like to delete Linux ISO's just because I currently don't need them. I might be the only one that still has that one ISO

Nice. That's the spirit! 👍🏻

> So this is how they appear!
> Is there another reason they could? Asking because they appear on my laptop too, but I don't run heavy software there (it couldn't bear it)

In rather rare cases the Portmaster might just fail to identify the process of a connection, but that is actually pretty solid now. Most connections you'll see there will be incoming connections that no process exists for. For example, when you get unsolicited packets on a port where no one is listening. So, of course, the Portmaster won't find a process for it.

But, we are still in alpha, and there might just be a bug somewhere too ;)

> Again, sorry for including everything in this one issue. Should I break them up into more issues in some way?

I think we're fine with this one and #203.

**Comment by MPeti1** [comment] 2020-11-28 17:43
> So the issue we are discussing is that you cannot stop and then start the Portmaster without reboot, correct? Because when you stop the Portmaster it marks the Kext for deletion?

Kext is (from right after installation) disabled and marked for deletion. Also, besides the reboot I need to run the installer again.

> For example, when you get unsolicited packets on a port where no one is listening. So, of course, the Portmaster won't find a process for it.

Most of them are incoming, but there are PTR querys, connections to domain names, and global P2P too.  I'll open an issue for it soon

**Comment by MPeti1** [comment] 2020-11-28 17:43
> So the issue we are discussing is that you cannot stop and then start the Portmaster without reboot, correct? Because when you stop the Portmaster it marks the Kext for deletion?

Kext is (from right after installation) disabled and marked for deletion. Also, besides the reboot I need to run the installer again.

> For example, when you get unsolicited packets on a port where no one is listening. So, of course, the Portmaster won't find a process for it.

Most of them are incoming, but there are PTR querys, connections to domain names, and global P2P too.  I'll open an issue for it soon

**Comment by dhaavi** [comment] 2020-12-01 19:24
> Kext is (from right after installation) disabled and marked for deletion. Also, besides the reboot I need to run the installer again.

This is really weird. I will investigate further in the coming days.

**Comment by MPeti1** [comment] 2020-12-04 16:07
I've experimented a bit with sysmon, and it turns out the only way to log service configuration change events with it is to log registry changes, which is not that useful because in most cases it will show that services.exe made the modification.

![image](https://user-images.githubusercontent.com/9215491/101181884-b57a3980-364d-11eb-9df4-54cbebef0dcd.png)

While looking in the system logs (Event Viewer\Windows Logs\System), I've found that the Service Control Manager logged that the PortmasterKext service was installed (by the timestamp I think that was after the reboot), with demand start start type, as it should be. But the next event is KProcessHacker3 service being installed, which I know I have been using for some time. Maybe they had the same problem and ended up doing this as a workaround?

PortmasterKext service installed | KProcessHacker3 service installed
:-:|:-:
![image](https://user-images.githubusercontent.com/9215491/101185096-bdd47380-3651-11eb-8cd6-49a5981ef655.png) | ![image](https://user-images.githubusercontent.com/9215491/101185507-3dfad900-3652-11eb-9186-2fa00bf86fa1.png)

Also, interestingly, the date and time of the event on the first screenshot is the same as on the second one, meaning that it was immediately disabled after being installed with the correct start type

**Comment by dhaavi** [comment] 2020-12-11 19:24
I had a first look at this and I think I now understand a little better what is happening.

At installation we only register one service: "Portmaster Core". This is the service that runs the main Portmaster process. It should always be enabled and set to the Start Type "Automatic".

The other service "Portmaster Kext" is a bit special. We cannot run a driver in Windows without it being tied to a service. But the driver itself is _not_ a service. We just load it on demand. It's not even properly registered.
So, what happens is that whenever the "Portmaster Core" service starts, it will then load the driver, which presents itself as the "Portmaster Kext" service. As this service is not registered, it will get marked for deletion as soon as the Portmaster stops.

What I don't understand, is that Windows then refuses to load the driver (which comes with that service).
Can you check if the issue persists with the latest Kext - [v1.0.7](https://github.com/safing/portmaster-windows-kext/releases/tag/v1.0.7)?

**Comment by MPeti1** [comment] 2020-12-12 15:27
I wasn't sure how to properly update the Kext, so I first updated Portmaster (by first uninstalling, and then installing 0.6.3), and it seems the problem has gone. Portmaster is in Secure state, the counters on the network monitor are changing, etc. I've rebooted, shut down and booted several times since install, and the Kext is always running now. It's still disabled, but it seems that's the correct behavior.

The only warning now is Limited Network Access with a green dot, but I'll open another issue for it

If you think so too, the issue can be closed :)

**Comment by MPeti1** [comment] 2020-12-12 15:37
No, it still seems to be a problem for when I try to restart the service from the settings menu.
Should I run the deploy.bat file from the sources of [v1.0.7](https://github.com/safing/portmaster-windows-kext/releases/tag/v1.0.7)?

**Comment by dhaavi** [comment] 2020-12-12 16:08
> I wasn't sure how to properly update the Kext, so I first updated Portmaster (by first uninstalling, and then installing 0.6.3)

Just starting the Portmaster or hitting the "Download Updates" button in the setting is enough. You'll need to restart the service in order to switch to a new version of the kext by pressing the "Restart" button.

> and it seems the problem has gone. Portmaster is in Secure state, the counters on the network monitor are changing, etc. I've rebooted, shut down and booted several times since install, and the Kext is always running now. It's still disabled, but it seems that's the correct behavior.

Nice!

> The only warning now is Limited Network Access with a green dot, but I'll open another issue for it

Yes, we are aware of that. You can open an issue if you want to track the progress.

> No, it still seems to be a problem for when I try to restart the service from the settings menu.

So, you mean if you click the "Restart" button on the settings page?

> Should I run the deploy.bat file from the sources of v1.0.7?

You would not be able to run it, as it needs to be signed by Microsoft and you'd need an EV Code Signing cert for that.

**Comment by dhaavi** [comment] 2020-12-12 16:54
You can always verify the current active and available versions in the version dropdown on the settings page.

**Comment by dhaavi** [comment] 2020-12-14 11:36
> > No, it still seems to be a problem for when I try to restart the service from the settings menu.
> 
> So, you mean if you click the "Restart" button on the settings page?

Duh. I don't know how, but I just failed to read that full sentence.

Interesting. I've never seen that happen. What might be happening is that the restart is too fast. Can you check if this also happens when you stop and then start the "Portmaster Core" service from the Windows Service Manager?

**Comment by MPeti1** [comment] 2020-12-14 15:25
> So, you mean if you click the "Restart" button on the settings page?

Yes

> You can always verify the current active and available versions in the version dropdown on the settings page.

The Kext is on 1.0.7 now

> Duh. I don't know how, but I just failed to read that full sentence.

No problem! Wanted to answer earlier, but couldn't reboot to test it because of the content of some opened notepad windows

> Can you check if this also happens when you stop and then start the "Portmaster Core" service from the Windows Service Manager?

If I stop it, wait a little, and start it, the Kext won't start along with it

**Comment by dhaavi** [comment] 2020-12-22 13:17
Thanks for confirming.

I had another look at this. And I think we might need to do some more unloading to completely remove the service after the driver was stopped. I will continue to investigate in January.

**Comment by dhaavi** [comment] 2021-02-10 12:15
I had another look at this and found something very interesting on StackOverflow. It seems that certain programs that monitor services can let a service hang in the "marked for deletion" state, thus preventing a restart of it, as per the original post of the question.

Quoting from https://stackoverflow.com/a/20565337:

> There may be several causes which lead to the service being stuck in “marked for deletion”.
> 
>  1. [SysInternals' Process Explorer is opened](http://blog.cyotec.com/2011/05/specified-service-has-been-marked-for.html). Closing it should lead to automatic removal of the service.
> 
>  1. [Task Manager is opened](https://stackoverflow.com/questions/20561990/how-to-solve-the-specified-service-has-been-marked-for-deletion-error/21310096#comment32672750_20565337).
> 
>  1. [Microsoft Management Console (MMC) is opened](https://stackoverflow.com/a/8529760/240613). To ensure all instances are closed, run `taskkill /F /IM mmc.exe`.
> 
>  1. [Services console is opened](https://stackoverflow.com/a/21310096/240613). This is the same as the previous point, since Services console is hosted by MMC.
> 
>  1. [Event Viewer is opened](https://stackoverflow.com/a/18467128/240613). Again, this is the same as the third point.
>  
>  1. [The key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\\{service name} exists](https://stackoverflow.com/a/2804099/240613).
> 
>  1. [Someone else is logged into the server](https://stackoverflow.com/a/28632820/240613) and has one of the previously mentioned applications opened.
> 
>  1. An instance of Visual Studio *used to debug the service* is open.

Can you check if any of these are running when you are trying to restart? Also, KProcessHacker3 might be running the background even when the Window is closed, monitoring services and causing this issue.

**Comment by MPeti1** [comment] 2021-02-10 13:58
Thank you! Also, I'm a bit ashamed that I wasn't able to find this SO question, despite it being very active.
Yes, I usually also run a regular task manager, but I suspect that PH can be part of it too, because that also monitors services. I'll try this out now

**Comment by MPeti1** [comment] 2021-02-10 15:03
After closing (Windows built-in) Task Manager AND Process Hacker*, Portmaster enters Secure state again, though only if I'm fast enough. But still, it seems a reboot is no longer required! :D

I noticed though that if I take too long to close the task managers (it's been too long if I already see the warning in the PM notifications section) PM will not try again, and both the "Restart" button in the settings, and the "Stop Portmaster" button in the 3 dots menu besides that won't work anymore.
In this case, manually restarting the `Portmaster Core` service (with task manager, PH, services.msc, etc but be sure to close it when done!) helps, it immediately recreates and starts `PortmasterKext` too, and Portmaster will work as if nothing has happened.

I would recommend that the core service should retry recreating the kext a few times (e.g. every 5 seconds for 5 tries), but creating the warning notification on the first failure. If you do this, it might be also a good idea to indicate somehow if PM is still trying, or it gave up, like by having a progress circle near the restart button with a tooltip that it's trying to restart

Also, now that it's confirmed that it's a Windows bug, there could be an entry for this in the [known issues](https://docs.safing.io/portmaster/install/windows#known-issues), so if someone else encounters this, it might be easier to find out about the behavior that way.

There's one more thing too: after the first time I stop task managers and restart PM successfully, if I reopen Process Hacker then the next 1 or 2 PM restart will go without problems. This should always involve the removal and recreation of the kext service, right? I checked in the event viewer, and the Service Control Manager (event id [7045](https://docs.microsoft.com/en-us/defender-for-identity/configure-windows-event-collection)) hasn't logged that the kext service would have been created for these occasions, while it did log it when I needed to close task managers for the restart to complete.
I wanted to let you know because I suspect that the restart button does not always work.

*If you have the same problem, be sure to close everything listed in the selected answer of the SO post linked in the comment above, and ALSO everything that you suspect can deal with services running on the system (like advanced process managers or other system management utilities).

**Comment by dhaavi** [comment] 2021-02-15 09:16
> Thank you! Also, I'm a bit ashamed that I wasn't able to find this SO question, despite it being very active.

No problem. I didn't find it the first time round either.

> I would recommend that the core service should retry recreating the kext a few times (e.g. every 5 seconds for 5 tries), but creating the warning notification on the first failure.

That is a good idea.

> having a progress circle near the restart button with a tooltip that it's trying to restart

This is a bit tricky. Maybe we'll find something to indicate that.

> Also, now that it's confirmed that it's a Windows bug, there could be an entry for this in the known issues, so if someone else encounters this, it might be easier to find out about the behavior that way.

👌

> I suspect that the restart button does not always work.

That _might_ be the case. We are switching to a new integration that will give feedback on whether it worked or not soon.

I'll close this now. Please reopen if the workaround stops working.

**Closed by dhaavi** 2021-02-15 09:16 UTC
Labels: bug
