### ISSUE TITLE
Windows: service names have broken encoding

### ISSUE THREAD

**Issue by northys** [safing/portmaster#225] opened 2021-01-01 22:52 UTC
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:

![image](https://user-images.githubusercontent.com/2878126/103447486-431c6980-4c8c-11eb-8676-e2976763b49b.png)

**What you expected to happen**:

Portmaster converts any random encoding to UTF-8 so it won't break later in dashboard.

**How to reproduce it (as minimally and precisely as possible)**:

* connect Czrch Win to internet and wait
* I bet Portmaster German Win would have problems with your üö signs

**Anything else we need to know?**:

**Environment**:

**Portmaster Version:**
 
I would love to =) #226

**Operating System:**
- [ ] Windows 7
- [ ] Windows 8/8.1
- [x] Windows 10
- [ ] Linux

If applicable you can provide related sections from the log files and ensure to **remove sensitive or otherwise private information**.
 - Linux: `/var/lib/portmaster/logs`
 - Windows: `%PROGRAMDATA%\Safing\Portmaster\logs`

**Comment by dhaavi** [comment] 2021-01-04 12:47
Huh. Yup, that should look better. Go is always UTF-8, but I think we can just adapt the output encoding of Powershell.

Can you execute the following in a Powershell window? I'm not sure the effect will be visible, but it just might.

```
Get-ItemProperty C:\Windows\System32\rundll32.exe | Select -ExpandProperty VersionInfo | Select -ExpandProperty FileDescription
[System.Console]::OutputEncoding = [System.Text.Encoding]::UTF8
Get-ItemProperty C:\Windows\System32\rundll32.exe | Select -ExpandProperty VersionInfo | Select -ExpandProperty FileDescription
```

> I bet Portmaster German Win would have problems with your üö signs

Everything I use is set to english. 😬 
And for some reason I can't change the language...

**Comment by northys** [comment] 2021-01-05 03:47
it's not broken

```
PS C:\Users\jirit> Get-ItemProperty C:\Windows\System32\rundll32.exe | Select -ExpandProperty VersionInfo | Select -ExpandProperty FileDescription                                                                                              Hostitelský proces systému Windows (Rundll32)                                                                           PS C:\Users\jirit> [System.Console]::OutputEncoding = [System.Text.Encoding]::UTF8                                      PS C:\Users\jirit> Get-ItemProperty C:\Windows\System32\rundll32.exe | Select -ExpandProperty VersionInfo | Select -ExpandProperty FileDescription                                                                                              Hostitelský proces systému Windows (Rundll32)                                                                           PS C:\Users\jirit>    
```



> Everything I use is set to english. 😬

#metoo but bullshitOS has licenced languages and my laptop has OEM licence of czech bullshitOS

>  And for some reason I can't change the language...

🙋‍♂️

**Comment by ppacher** [comment] 2021-01-05 07:42
Windows uses UTF-16 a lot (at least kernel strings are UTF-16 most of the time). It might be that powershell also outputs in UTF-16 in which case we would need to convert it's stout/err using `syscall.UTF16ToString` . On my phone right now so I cannot check

**Comment by northys** [comment] 2021-01-05 14:44
Gosh =)

**Comment by ppacher** [comment] 2021-01-08 12:03
This will be fixed with safing/portbase#112 once merged. We'll notify you once it's released.

**Comment by northys** [comment] 2021-01-09 13:44
You execute powershell to get data on windows?

**Comment by dhaavi** [comment] 2021-01-25 16:34
> You execute powershell to get data on windows?

Only for some weird stuff that can only be done easily in C#. All the important stuff is done directly with the DLLs.

**Comment by northys** [comment] 2021-01-25 16:42
What a cute OS =)

**Comment by dhaavi** [comment] 2021-02-15 08:49
A first fix for this is live with [v0.6.5](https://github.com/safing/portmaster/releases/tag/v0.6.5), but this does not fix the issue entirely, there seems to be a UI side of this too. We are further working on a fix.

We were also able to reproduce the behavior, so we'll be able to confirm the fix ourselves. Thank you for your support.

**Comment by dhaavi** [comment] 2021-03-11 15:57
This was fixed in [ui/portmaster-v0.1.5](https://github.com/safing/portmaster-ui/releases/tag/portmaster-v0.1.5), which was released today.

Please report back if this works for you as expected.
In order to trigger re-fetching of the process/binary name, you'll need to delete the profile and wait for it to be regenerated and reassigned to the process - just check back later. 😉

**Comment by dhaavi** [comment] 2021-03-29 13:08
@northys Is this resolved?

**Comment by northys** [comment] 2021-03-29 14:51
@dhaavi I love myself so much that I haven't been in Windows for a long time... I'll check when I boot it and install all the remaining updates =)

**Comment by dhaavi** [comment] 2021-03-30 09:04
I see. :grin:
Then I'll just leave this open until you have the time - no problem.

**Comment by aleksia123** [comment] 2021-04-01 10:26
Marking this enabled might fix your issue:

![portmaster](https://user-images.githubusercontent.com/59471962/113281056-a2623800-92d4-11eb-96de-6a3b6f47d28a.JPG)

**Comment by dhaavi** [comment] 2021-04-01 11:01
Hey @aleksia123, thanks for the hint. That is a very interesting option.

In this special case we already tell the powershell to output in UTF-8 - I don't know if this setting would change anything there.
It definitely is an interesting workaround for this or future encoding issues.

**Comment by northys** [comment] 2021-04-01 21:54
> Hey @aleksia123, thanks for the hint. That is a very interesting option.

The option could be called "unbullshit my os "

**Comment by northys** [comment] 2021-04-04 16:24
I had portmaster uninstalled and when I install it the networking doesn't work. Sorry but I'm not willing to debug it for now. The OS just prints random errors every time I do something so it has to be fixed with reinstall as usually. So maybe after a year, maybe two... :)

**Comment by dhaavi** [comment] 2021-04-06 08:37
Haha, ok. No problem.

Then I'll just close this for now, as from all we know, the issue has been resolved.

**Comment by northys** [comment] 2021-04-11 12:04
@dhaavi after reinstall with Czech language I see English service names in Portmaster. Is it expected behaviour?

**Comment by dhaavi** [comment] 2021-04-12 08:55
No, this is not expected. As far as I understand you had Czech language output before. Can you check what it now tells you for the exact binary you created the issue with? Don't know how to get that to do something on the network, though.

Afaict, we didn't change anything that could trigger that. Maybe it was that recent Windows update? It broke other parts of the Portmaster too.

Did you enable language support like mentioned [above](https://github.com/safing/portmaster/issues/225#issuecomment-811813235)? If you go there, what does it tell you?

**Comment by northys** [comment] 2021-04-12 23:33
I was confused by the first "System DNS Client" App. After a while a first check system looking entry appeared. Sadly, there is no diacritics 🙄 

I can't see rundll32.exe right now even an hour after system startup.

![image](https://user-images.githubusercontent.com/2878126/114475167-07ccf780-9bf8-11eb-8d88-a7a7d3d06565.png)

**Comment by dhaavi** [comment] 2021-04-14 13:14
I checked with a system of mine and it does load some german names.

Can you compare the names using the [Sysinternal's Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer)? It nicely shows the correct name in the `Description` field.

**Closed** 2021-05-17 10:45 UTC
Labels: bug, waiting for input
