### ISSUE TITLE
svchost DNS53 is blocked not redirected

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#844] opened 2022-09-08 13:55 UTC
![XXX](https://user-images.githubusercontent.com/62152714/189140415-0b26f760-7ca0-4daa-927a-8436e355ba99.png)

One of the devs said all 853 and 53 request from all programs are redirected to Postmaster to resolve.

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Rexadev** [comment] 2022-09-11 13:38
Also it shows as P2P nor DNS request

**Comment by dhaavi** [comment] 2022-09-14 08:49
Do you have [Seamless DNS Integration](https://docs.safing.io/portmaster/settings#filter/dnsQueryInterception) disabled?

If not, please provide the debug info from when this is occuring.

**Comment by Rexadev** [comment] 2022-09-14 09:54
> Do you have [Seamless DNS Integration](https://docs.safing.io/portmaster/settings#filter/dnsQueryInterception) disabled?

No, I don't even know how to turn it off?

> If not, please provide the debug info from when this is occuring.

Ok when i see it

**Comment by Rexadev** [comment] 2022-09-17 13:02
Turned on dev mode and No it is not turned Off

**Comment by Rexadev** [comment] 2022-09-17 15:46
![image](https://user-images.githubusercontent.com/62152714/190865175-c5e75d67-77ee-47cc-938d-1f8603999e3e.png)

**Comment by Rexadev** [comment] 2022-09-18 11:49
![image](https://user-images.githubusercontent.com/62152714/190900567-0d5a46de-2f06-4d3a-b08f-ec92335d2518.png)

**Comment by Rexadev** [comment] 2022-09-18 18:55
![image](https://user-images.githubusercontent.com/62152714/190923798-0ac15cca-6483-4e00-bc0c-c88ff259a742.png)

**Comment by ppacher** [comment] 2022-09-22 10:54
Ok, the issue here is that you [Force Block P2P/Direct Connections](https://docs.safing.io/portmaster/settings#filter/blockP2P) from svchost. Since that setting is enabled the DNS request is never allowed to be sent so the Portmaster won't intercept it and answer it on it's own. 

Not sure what you try to say with the other screenshots but everything here is working as intended. Hence, I'm closing this one.

Feel free to continue posting here if something is unclear or to re-open if there's something I missed.

**Closed by ppacher** 2022-09-22 10:54 UTC
Labels: bug

**Comment by Rexadev** [comment] 2022-09-22 13:31
Here https://github.com/safing/portmaster/issues/844#issuecomment-1250253078 Some are blocked Some are not

@ppacher
