### ISSUE TITLE
Windows Crash

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1039] opened 2022-12-13 10:58 UTC
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
![image](https://user-images.githubusercontent.com/62152714/207299343-1afe2595-b289-4343-8767-d25160440737.png)

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by dhaavi** [comment] 2022-12-13 12:34
Duplicate of https://github.com/safing/portmaster/issues/1019.

Please do not use the Staging release channel.

**Closed by dhaavi** 2022-12-13 12:34 UTC
Labels: bug

**Comment by Rexadev** [comment] 2022-12-13 12:41
> Duplicate of #1019.
> 
> Please do not use the Staging release channel.

I am on Beta
