### ISSUE TITLE
arch aur pakage is outdated

### ISSUE THREAD

**Issue by Aneeqasif** [safing/portmaster#1063] opened 2023-01-16 12:51 UTC
https://aur.archlinux.org/packages/portmaster-stub-bin

https://aur.archlinux.org/pkgbase/portmaster-stub-bin/flag-comment

![image](https://user-images.githubusercontent.com/78728701/212682335-ad12ec5f-bd97-4859-ae99-377413f5c99a.png)

**Comment by LordDemecrius83** [comment] 2023-01-16 18:48
It's just a stub binary that pulls in the latest version of portmaster

**Comment by Aneeqasif** [comment] 2023-01-18 10:07
the link in aur pakage is broken i guess

**Comment by Aneeqasif** [comment] 2023-01-18 10:08
> It's just a stub binary that pulls in the latest version of portmaster

anyways please update the pkgbuild to latest version number to avoid confusion and also check if the pkgbuild is right or not because the link to fetch items in pkgbuild is dependent on version number variable

**Comment by dhaavi** [comment] 2023-03-06 13:10
Duplicate of https://github.com/safing/portmaster-packaging/issues/80.

**Closed by dhaavi** 2023-03-06 13:10 UTC
Labels: bug
