### ISSUE TITLE
Add option to throttle apps and connections

### ISSUE THREAD

**Issue by JamesYeoman** [safing/portmaster#893] opened 2022-09-24 12:40 UTC
**What would you like to add or change?**:
An option across the board (globally, per-app, and per-connection) to throttle the bandwidth used.

**Why do you and others need this?**:
Many home routers lack the ability to cap network speeds per device, and some even allow all bandwidth to be allocated to a single device if such device demands it. As a result, I have to manually throttle Steam downloads. But it's not just Steam that can saturate an entire home network's bandwidth.

The ability to limit the total device bandwidth would be a boon, and the ability to throttle badly behaving apps would also be useful. My personal use-case is just for making sure I don't accidently cause slowdowns for everyone else on the network. However, I can see this being useful for allowing multiple bandwidth-hungry apps running at the same time without saturating each-other

**Comment by Rexadev** [comment] 2022-09-24 16:27
Related https://github.com/safing/portmaster/issues/382

**Comment by davegson** [comment] 2023-01-19 15:25
duplicate of #382

**Closed by davegson** 2023-01-19 15:25 UTC
Labels: suggestion
