### ISSUE TITLE
First day enduser issues

### ISSUE THREAD

**Issue by blindside1** [safing/portmaster#43] opened 2020-04-24 21:52 UTC
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [ ] I searched for similar/existing issues first.
- [ ] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:
I installed Portmaster, and then when I tried to spin up my VPN, it couldn’t connect. I also am experiencing speed issues with my data. It’s half what it should be. Also, when click any of the links on the support section of Portmaster, I error out. (I was able to finally get the popup  to go away by clicking yes a bunch of times) I am attaching screenshots at the bottom.

**What you expected to happen**:
 I expected there to be issues with my VPN, but I wasn’t sure if my speed would be affected by half.

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**:
I am still very interested in acting as one of your nodes! On twitter I am blindside0x01

**Environment**:Win10 Pro. All updates applied

Portmaster Version: 0.4.0 pre-Alpha

<details>
  <summary>Versions from the `About` page in Portmaster's UI</summary>
  
</details>

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [x] Windows 10
- [ ] Linux
  - Please provide the output of `cat /etc/os-release`

If applicable you can provide related sections from the log files and ensure to **remove sensitive or otherwise private information**.
 - Linux: `/var/lib/portmaster/logs`
 - Windows: `%PROGRAMDATA%\Portmaster\ļogs`

NJ{"Created":1587760483,"Modified":1587760483,"Expires":1590352483,"Deleted":0}S
executing app/portmaster-app.exe version 0.1.7 on windows amd64
![SpeedtestOOKLA-Safing 2020-04-24](https://user-images.githubusercontent.com/48873350/80259557-7296c300-8675-11ea-85a6-fe47246da3d6.png)

![RedditBugSafing 2020-04-24](https://user-images.githubusercontent.com/48873350/80259630-9ce88080-8675-11ea-9380-57d9a521b0dd.png)

![AirVPNBugSafing](https://user-images.githubusercontent.com/48873350/80259700-bab5e580-8675-11ea-953e-4766b56d3110.png)

**Comment by dhaavi** [comment] 2020-04-25 07:23
Hey @blindside1, welcome aboard!

There are multiple things going on here, I will try to address them separately:

__First:__

> I installed Portmaster, and then when I tried to spin up my VPN, it couldn’t connect.

This is probably due to your VPN trying connect directly to a server without resolving an IP address first. We call these `direct`, `peer to peer` or `P2P` connections. Except for special situations like yours, this is actually uncommon behaviour, not seldomly used by malware.
You can confirm this by opening up the "Monitor" page in the UI and it will tell you why a connection was blocked.
If it actually was the P2P blocking that prevents your VPN software from connecting, you can change this setting in the "Settings" page.

__Second:__

> I also am experiencing speed issues with my data. It’s half what it should be.

This definitely should not happen. After evaluating a connection, control is essentially handed to the Kernel (Extension), which should easily handle Gigabit speeds. Please continue testing and report back. I will keep this in the back of my head and think about it.

__Third:__

> Also, when click any of the links on the support section of Portmaster, I error out. (I was able to finally get the popup to go away by clicking yes a bunch of times) I am attaching screenshots at the bottom.

This is unintended behavior. The Portmaster UI runs in a OS-provided browser view (no Electron!) and therefore it just loads external URLs in there, which, of course, it shouldn't. Because it tries to load inside the UI, you get all these errors. We are working on a fix that will come out early next week. Until then, please copy the URL and paste it into your preferred browser.

__Other:__

I am a bit confused that you state you are running version `0.4.0`, you actually should be running `0.4.1`. Could you open the about page and paste the full version information here? (Just select all the version information with your mouse and copy it)

**Comment by ppacher** [comment] 2020-04-25 08:38
Thanks for reporting this @blindside1 . For reference, I created a dedicated UI issue for the support links problem at https://github.com/safing/portmaster-ui/issues/49

**Comment by blindside1** [comment] 2020-04-25 23:44
Thanks so much for the responses. I will work on this after I spin up another machine that I'm going to use solely for testing. As far as the "Other" question, I downloaded what was offered. There *is* a good chance I wrote the version # wrong. Once again, thanks for getting back with me.

**Comment by dhaavi** [comment] 2020-05-27 15:27
Hey @blindside1, sorry for the long delay. We worked on lots of fixes. Please update to the newest version and try again. Everything should work now - and if not, please report back.

**Comment by dhaavi** [comment] 2020-07-17 05:10
Closing due to age and outdated version. Please report continued issues here or open a new issue.

**Closed by dhaavi** 2020-07-17 05:10 UTC
Labels: bug
