### ISSUE TITLE
How do i use Portmaster with ISPs DNS Server and which Networkadaptersettings can be disabled?

### ISSUE THREAD

**Issue by FrostBlade5** [safing/portmaster#742] opened 2022-07-14 11:31 UTC
Portmaster offers four DNS Server options, cloudflare, quad9, adguard, foundation for applied privacy.
My VPN provider suggested to use my ISPs DNS server so their DNS Server will overwrite my ISP, this is not possible with portmaster because it overwrites the VPNs DNS Server.
So what i tried to do is simply remove the pre-selected dns server from portmaster and leave this setting blank, i tought this will automatically set my dns server to my ISPs DNS however after changing this setting to blank i cannot connect to any website on any browser. It seems the blank setting removes the dns server and without one i cant browse the web, however for some reason i was able to connec to my VPN provider but even than i could not reach any website.

Next question, normally i disable all options under windows network adapter settings expect ipv4 since this is the only setting require to go online. However now after installing portmaster i noticed some setting have re-enabled themselfes.
I will try to disable those again and see what happens but for privacy and security reasons i want to as you which of those settings are essentials to guarantee portmasters funtionallity?
[](url)

**Comment by FrostBlade5** [comment] 2022-07-14 11:33
How can i use portmaster with my ISPs DNS Server in order to overwrite that with my VPNs DNS Server to guarante privacy?

[https://i.postimg.cc/XvW54vfG/Capture3.png](url)
[https://i.postimg.cc/y8cRMRZC/Capture2.png](url)
[https://i.postimg.cc/8PqWX4sb/Capture.png](url)

**Comment by davegson** [comment] 2022-07-28 17:16
I think this is a duplicate of #754, hence I am closing with this note here too:

A conversation about _why_ we make it hard to disable Secure DNS - basically it would remove the ability to block a lot of the nasty trackers based on the filter lists.
https://github.com/safing/portmaster/issues/677#issuecomment-1145215982

if you disagree let me know and I'll consider re-opening it

we can continue the compatibility issue in #734

**Closed by davegson** 2022-07-28 17:16 UTC
Labels: suggestion
