### ISSUE TITLE
Automatically update path for updated UWP apps

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#836] opened 2022-09-06 18:20 UTC
![image](https://user-images.githubusercontent.com/62152714/188709951-d274ed66-a1a7-404f-aea1-1cf785801d25.png)

**What would you like to add or change?**:

**Why do you and others need this?**:

**Comment by ppacher** [comment] 2022-09-25 17:54
This also seems to be a duplicate of https://github.com/safing/portmaster/issues/485

**Closed by ppacher** 2022-09-25 17:54 UTC
Labels: suggestion

**Comment by Rexadev** [comment] 2022-10-11 16:13
@dhaavi Related? https://github.com/safing/portmaster/commit/c22fb3316b33d5a2d00ce054d88651102c75c46c
