### ISSUE TITLE
Limit Internet speed of specific programs

### ISSUE THREAD

**Issue by Z3r0ut** [safing/portmaster#663] opened 2022-05-22 09:54 UTC
**What would you like to add or change?**:
Limit the speed of specific programs, for example limit a Webbrowser to max 1MB/s download

**Why do you and others need this?**:
I and others would need this for programs that use the Internet but do not have a speed limiter, for some reason.

**Comment by p2anav** [comment] 2022-05-23 06:14
The Portmaster was not designed for this but we will surely think about it. Thanks for your suggestion I will pass to the team.

**Comment by itsnotsaved** [comment] 2022-05-24 01:17
Duplicate of #382

**Comment by davegson** [comment] 2022-06-23 08:10
closing as it's a duplicate - thanks @itsnotsaved

**Closed by davegson** 2022-06-23 08:10 UTC
Labels: suggestion
