### ISSUE TITLE
Backup/Restore of Configurations

### ISSUE THREAD

**Issue by Zeik0s** [safing/portmaster#561] opened 2022-03-06 19:35 UTC
**What would you like to add or change?**:
I would like a function to backup and restore the filter set or at best all configurations i made in Portmaster. 

**Why do you and others need this?**:

Because much time is spent on creating them and would be spent again if i'm restoring my PC from a backup for example.
Also a second effect of this could be shared configurations as sort of baselines, which lowers the entry bar for using portmaster.

**Comment by northys** [comment] 2022-03-07 21:47
I think that for now you can just backup `/opt/safing/portmaster/databases/core/bbolt` and `/opt/safing/portmaster/config.json` but I agree that some kind of automatic daily one-file-backup would be great!

**Comment by dhaavi** [comment] 2022-03-25 15:48
@Zeik0s and @northys, this is something we have been planning for some time now. Can't say when, but the priority is quite high.

**Comment by Rexadev** [comment] 2022-10-11 16:14
@dhaavi related? https://github.com/safing/portmaster/commit/617644c1939d6b01c717c2ac73f52f12c9d88249

**Comment by Raphty** [comment] 2023-10-06 07:28
duplicate of #388

**Closed by Raphty** 2023-10-06 07:28 UTC
Labels: suggestion
